plugins {
    id 'java'
    id 'java-library'
    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

version = "${minecraft_version}-${mod_version}"
group = 'org.dave.compactmachines3'

base {
    archivesName.set('compactmachines3')
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

minecraft {
    mcVersion.set(minecraft_version)
    mcpMappingChannel.set('stable')
    mcpMappingVersion.set('39')
}

repositories {
    maven {
        name = 'CleanroomMC Maven'
        url = 'https://maven.cleanroommc.com'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'CleanroomMC CurseMaven'
                url = 'https://curse.cleanroommc.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    mavenLocal()
}

dependencies {
    implementation rfg.deobf('curse.maven:jei-238222:5846804')
    implementation rfg.deobf('curse.maven:hwyla-253449:2568751')
    implementation rfg.deobf('curse.maven:topce-885670:7129885')
    implementation rfg.deobf('curse.maven:refinedstorage-243076:2940914')
    compileOnly files('lib/OpenComputers-223008-6608365.jar')
    compileOnly files('lib/RedstoneFlux-1.12-2.1.1.1-universal.jar')
    runtimeOnly files('lib/RedstoneFlux-1.12-2.1.1.1-universal.jar')

    implementation(rfg.deobf('curse.maven:ThermalDynamics-227443:2920505')) {
        transitive = false
    }
    implementation(rfg.deobf('curse.maven:CoFHCore-69162:2920433')) {
        transitive = false
    }

    runtimeOnly(rfg.deobf('curse.maven:ThermalFoundation-222880:2926428')) {
        transitive = false
    }
    runtimeOnly(rfg.deobf('curse.maven:thermal-expansion-69163:2926431')) {
        transitive = false
    }
    runtimeOnly(rfg.deobf('curse.maven:ThermalCultivation-271835:2920437')) {
        transitive = false
    }
    runtimeOnly(rfg.deobf('curse.maven:CoFHWorld-271384:2920434')) {
        transitive = false
    }
    runtimeOnly(rfg.deobf('curse.maven:CodeChickenLib-242818:2779848')) {
        transitive = false
    }

    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(8)
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile).configureEach {
        javaCompiler.set(javaToolchains.compilerFor {
            languageVersion.set(JavaLanguageVersion.of(25))
        })
        options.release.set(8)
    }
}

tasks.named('injectTags').configure {
    it.tags.set(['VERSION': mod_version])
    it.outputClassName.set('org.dave.compactmachines3.Tags')
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', minecraft_version

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': minecraft_version
    }
}

tasks.register('deobfJar', Jar) {
    from sourceSets.main.output
    archiveClassifier.set('deobf')
}
