buildscript {
    repositories {
        jcenter()
        maven {
            name = "forge"
            url = "https://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "${minecraft_version}-${mod_version}"
group = "org.dave.compactmachines3" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "compactmachines3"

sourceCompatibility = targetCompatibility = "1.8" // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    version = "1.12.2-14.23.5.2831"
    runDir = "run"

    mappings = "stable_39"

    replaceIn "CompactMachines3.java"
    replace "@VERSION@", project.mod_version
}

repositories {
    repositories {
        maven {
            url "https://cursemaven.com"
        }
    }
}

dependencies {

    deobfCompile ("curse.maven:jei-238222:5846804")
    deobfCompile ("curse.maven:hwyla-253449:2568751")
    deobfCompile ("curse.maven:topce-885670:7129885")
    deobfCompile ("curse.maven:refinedstorage-243076:2940914")
    deobfCompile ("curse.maven:OpenComputers-223008:6608365")

    // All of the following are needed to make Ducts connect to each other visually
    // in recipes and in the machine view. :(
    deobfCompile("curse.maven:ThermalDynamics-227443:2920505") {
        transitive = false
    }
    deobfCompile("curse.maven:CoFHCore-69162:2920433") {
        transitive = false
    }

    // And some runtime-dependencies for the above two libraries.
    runtime("curse.maven:ThermalFoundation-222880:2926428") {
        transitive = false
    }
    runtime("curse.maven:thermal-expansion-69163:2926431") {
        transitive = false
    }
    runtime("curse.maven:ThermalCultivation-271835:2920437") {
        transitive = false
    }
    runtime("curse.maven:CoFHWorld-271384:2920434") {
        transitive = false
    }
    runtime("curse.maven:CodeChickenLib-242818:2779848") {
        transitive = false
    }
}

allprojects {
    if (System.getenv("TRAVIS") != null) {
        def tag = System.getenv("TRAVIS_TAG");
        if (tag != null && !tag.isEmpty() && tag.contains("release")) {
            project.ext.releaseType = "release"
        } else {
            version += "-b${System.getenv("TRAVIS_BUILD_NUMBER")}"
            project.ext.releaseType = "beta"
        }
    }
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
